### ISSUE TITLE
Several failing packages don't seem to run tests at all; end with `cat: 'dev/log/testpackage1*.corelg': No such file or directory`

### ISSUE THREAD

**Issue by fingolfin** [gap-infra/actions#6]
See e.g. [this log](https://github.com/gap-infra/integration/runs/5294942688?check_suite_focus=true) which ends with
```
cat: 'dev/log/testpackage1*.corelg': No such file or directory
```
Presumably because `make testpackage PKGNAME=$PKG_NAME` is used (see also #1 -- we shouldn't do this anymore) and fails to produce something. We can't see why, though. Perhaps some dependency is missing / was not compiled?

I suspect this will become easy to deal with once we resolved #1. Seems I always circle back to that :-)

**Comment by wilfwilson** [comment]
This issue may be related to https://github.com/gap-packages/gap-packages.github.io/issues/9

**Comment by olexandr-konovalov** [comment]
[That issue](https://github.com/gap-packages/gap-packages.github.io/issues/9) wrongly marks CoReLG tests as done, but they are not: they have tests in `tst` to please the CI, but they don't have their default test specified in `PackageInfo.g`, what is expected by `make testpackages` and `make testpackage PKGNAME=$PKG_NAME`.

I've unchecked that tickbox there.

**Comment by fingolfin** [comment]
@alex-konovalov no, corelg does not specify a TestFile (the latest version does, though) and hence passes all its tests (see issue #10)

**Comment by fingolfin** [comment]
Anyway, we are not using `make testpackage(s)` anymore which resolved a number of problems :-)
